fontforge.View.DefaultFont: 400 12pt system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.View.LabelFont: 400 12pt Deja Vu Sans,Lucida Grande,unifont,unifont upper
fontforge.View.MonoFont: 400 12pt monospace,unifont
fontforge.View.SerifFont: 400 12pt serif
fontforge.View.Background: #f2f2f2

fontforge.FontView.GlyphFGColor: #000000
fontforge.FontView.GlyphInfoColor: #4581d3
fontforge.FontView.SlotOutlineColor: #000000
fontforge.FontView.SlotDivisionColor: #808080
fontforge.FontView.LabelColor: #000000
fontforge.FontView.UnencodedLabelColor: #505050
fontforge.FontView.MissingLabelColor: #ff4f4f
fontforge.FontView.EmptySlotFgColor: #d4d4d4
fontforge.FontView.SelectedColor: #7ba5de
fontforge.FontView.SelectedFgColor: #000000
fontforge.FontView.ChangedColor: #0f6bcf
fontforge.FontView.MissingBitmapColor: #ff0000
fontforge.FontView.MissingOutlineColor: #008000
fontforge.FontView.HintingNeededColor: #ff4f69
fontforge.FontView.MetricsAdvanceAtColor: #008000
fontforge.FontView.MetricsAdvanceToColor: #008000
fontforge.FontView.MetricsBaselineColor: #0000c0
fontforge.FontView.MetricsOriginColor: #c00000
fontforge.FontView.MetricsGlyphContourColor: #a45a38
fontforge.FontView.Font: 400 12pt system-ui,Deja Vu Sans,Lucida Grande,sans

fontforge.CharView.PointColor: #ff0000
fontforge.CharView.FirstPointColor: #0000ff
fontforge.CharView.SelectedPointColor: #1514f4
fontforge.CharView.SelectedPointWidth: 2
fontforge.CharView.ExtremePointColor: #c00080
fontforge.CharView.PointOfInflectionColor: #008080
fontforge.CharView.AlmostHVColor: #00ff80
fontforge.CharView.NextCPColor: #007090
fontforge.CharView.PrevCPColor: #ff0000
fontforge.CharView.SelectedCPColor: #ffffff
fontforge.CharView.AnchorColor: #0040ff
fontforge.CharView.LabelFont: 400 10pt system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.CharView.IconFont: 400 24pt serif
fontforge.CharView.PointNumberFont: 400 10px system-ui,Deja Vu Sans,Lucida Grande,sans

fontforge.CharView.ForegroundOutlineColor: #000000
fontforge.CharView.ForegroundThickOutlineColor: #20707070
fontforge.CharView.FillColor: #80707070
fontforge.CharView.PreviewFillColor: #fe000000
fontforge.CharView.OpenPathColor: #40660000
fontforge.CharView.ClipPathColor: #0000ff
fontforge.CharView.BackgroundOutlineColor: #4581d3
fontforge.CharView.BackgroundThickOutlineColor: #20707070
fontforge.CharView.WidthColor: #000000
fontforge.CharView.WidthSelColor: #00ff00
fontforge.CharView.LBearingSelColor: #00ff00
fontforge.CharView.LigatureCaretColor: #909040
fontforge.CharView.AnchoredOutlineColor: #0040ff
fontforge.CharView.CoordinateLineColor: #808080
fontforge.CharView.AscentDescentColor: #ff808080
fontforge.CharView.ItalicCoordColor: #909090
fontforge.CharView.MetricsLabelColor: #000000
fontforge.CharView.TemplateOutlineColor: #4581d3
fontforge.CharView.RulerBigTickColor: #4581d3
fontforge.CharView.RulerCurrentTickColor: #ff0000
fontforge.CharView.Ruler Font: 400 10px system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.CharView.GuideOutlineColor: #808080
fontforge.CharView.GuideDragColor: #000000

fontforge.CharView.TraceColor: #4581d3
fontforge.CharView.OldOutlineColor: #4581d3
fontforge.CharView.TransformOriginColor: #000000
fontforge.CharView.DraggingComparisonOutlineColor: #8800bb00
fontforge.CharView.DraggingComparisonAlphaChannelOverride: #88000000
fontforge.CharView.MeasureToolLineColor: #000000
fontforge.CharView.MeasureToolPointColor: #ff0000
fontforge.CharView.MeasureToolPointSnappedColor: #00ff00
fontforge.CharView.MeasureToolCanvasNumbersColor: #ff0000
fontforge.CharView.MeasureToolCanvasNumbersSnappedColor: #00ff00
fontforge.CharView.MeasureToolWindowForeground: #000000
fontforge.CharView.MeasureToolWindowBackground: #e0e0c0
fontforge.CharView.MeasureToolFont: 400 12px monospace,unifont

fontforge.CharView.BlueValuesStippledColor: #808080ff
fontforge.CharView.FamilyBlueStippledColor: #80ff7070
fontforge.CharView.MDHintColor: #80e04040
fontforge.CharView.HintLabelColor: #00cccc
fontforge.CharView.DHintColor: #80d0a0a0
fontforge.CharView.HHintColor: #80a0d0a0
fontforge.CharView.VHintColor: #80c0c0ff
fontforge.CharView.HFlexHintColor: #00ff00
fontforge.CharView.VFlexHintColor: #00ff00
fontforge.CharView.ConflictHintColor: #00ffff
fontforge.CharView.HHintActiveColor: #00a000
fontforge.CharView.VHintActiveColor: #0000ff
fontforge.CharView.DeltaGridColor: #cc0000

fontforge.CharView.GridFitOutlineColor: #4581d3
fontforge.CharView.GridFitWidthColor: #4581d3
fontforge.CharView.RasterColor: #ffa0a0a0
fontforge.CharView.RasterNewColor: #ff909090
fontforge.CharView.RasterOldColor: #ffc0c0c0
fontforge.CharView.RasterGridColor: #ffb0b0ff
fontforge.CharView.RasterDarkColor: #ff606060
fontforge.CharView.BackgroundImageColor: #fe707070

fontforge.CharView.CVPaletteForegroundColor: #d4d4d4
fontforge.CharView.CVPaletteBackgroundColor: #333333
fontforge.CharView.Button3DEdgeLightColor: #e0e0e0
fontforge.CharView.Button3DEdgeDarkColor: #707070
fontforge.CharView.Button3d: True
fontforge.CharView.LayersPalette.Font: 400 10px system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.CharView.ToolsPalette.Font: 400 10px system-ui,Deja Vu Sans,Lucida Grande,sans

fontforge.BitmapView.BitmapColor: #909090
fontforge.BitmapView.OverviewColor: #d4d4d4
fontforge.BitmapView.GuideColor: #e33439
fontforge.BitmapView.WidthGuideColor: #404040
fontforge.BitmapView.GridColor: #999999
fontforge.BitmapView.OutlineColor: #03a3ee
fontforge.BitmapView.ActiveToolColor: #106ad0
fontforge.BitmapView.SelectedRegionColor: #106ad0
fontforge.BitmapView.ReferenceColor: #808080
fontforge.BitmapView.SelectedReferenceColor: #106ad0
fontforge.BitmapView.ReferenceBorderColor: #09478d
fontforge.BitmapView.SelectedReferenceBorderColor: #09478d

fontforge.MetricsView.Font: 400 12px system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.MetricsView.GlyphColor: #000000
fontforge.MetricsView.SelectedGlyphColor: #2b2b2b
fontforge.MetricsView.DividerColor: #d4d4d4
fontforge.MetricsView.AdvanceWidthColor: #80827c
fontforge.MetricsView.ItalicAdvanceColor: #80827c
fontforge.MetricsView.KernLineColor: #3d7905
fontforge.MetricsView.SideBearingLineColor: #12376c

fontforge.BDFProperties.Font: 400 10pt system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.Combinations.Font: 400 12px system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.CVT.Font: 400 12px monospace,unifont
fontforge.FontInfo.OriginLineColor: #808080
fontforge.FontInfo.Font: 400 12pt system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.GlyphInfo.Font: 400 12pt monospace,unifont
fontforge.Groups.Font: 400 12pt system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.Histogram.GraphColor: #2020ff
fontforge.Histogram.Font: 400 10pt system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.KernClass.TextColor: #006080
fontforge.KernClass.Font: 400 12pt monospace,unifont
fontforge.KernFormat.Font: 400 12pt system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.KernFormat.BoldFont: 700 12pt system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.Math.Font: 400 12pt system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.Math.BoldFont: 700 12pt system-ui,Deja Vu Sans,Lucida Grande,sans

fontforge.Prefs.MonoFont: 400 12pt monospace,unifont
fontforge.SearchView.Font: 400 12pt system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.SearchView.BoldFont: 700 12pt system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.ShowAtt.SelectColor: #ff4f4f
fontforge.ShowAtt.GlyphNameColor: #0000ff
fontforge.ShowATT.Font: 400 12pt system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.ShowATT.MonoFont: 400 12pt monospace,unifont
fontforge.StateMachine.Font: 400 12pt monospace,unifont
fontforge.TTInstruction.Font: 400 12px monospace,unifont
fontforge.Validate.Font: 400 11pt system-ui,Deja Vu Sans,Lucida Grande,sans
fontforge.Warnings.Font: 400 10pt system-ui,Deja Vu Sans,Lucida Grande,sans

fontforge.Splash.Foreground: #d4d4d4
fontforge.Splash.Background: #333333
fontforge.Splash.Font: 400 10pt serif
fontforge.Splash.ItalicFont: 400 10pt italic serif
fontforge.Splash.MonoFont: 400 10pt monospace,unifont
fontforge.Splash.Image: splash2019.png

fontforge.SFTextArea.Box.ActiveInner: True
fontforge.SFTextArea.Box.Padding: 1
fontforge.SFTextArea.Font: 400 10pt monospace,unifont

Gdraw.Background: #333333
Gdraw.Foreground: #d4d4d4
Gdraw.WarningForeground: #bd4337
Gdraw.ScreenResolution: 0
Gdraw.MultiClickTime: 200
Gdraw.MultiClickWiggle: 3
Gdraw.SelectionNotifyTimeout: 2
Gdraw.TwoButtonFixup: True
Gdraw.MacOSXCmd: True
Gdraw.Synchronize: False

Gdraw.GGadget.Popup.Font: 400 10pt Sans, Lucida Grande, Arial, Helvetica Neue
Gdraw.GGadget.Popup.Foreground: #d4d4d4
Gdraw.GGadget.Popup.Background: #333333
Gdraw.GGadget.Popup.Delay: 1000
Gdraw.GGadget.Popup.LifeTime: 20000

Gdraw.GProgress.Font: 400 10pt Sans, Lucida Grande, Arial, Helvetica Neue
Gdraw.GProgress.Foreground: #d4d4d4
Gdraw.GProgress.FillColor: #0f6bcf
Gdraw.GProgress.Background: #333333

Gdraw.GGadget.Box.BorderInner: False
Gdraw.GGadget.Box.BorderOuter: False
Gdraw.GGadget.Box.ActiveInner: False
Gdraw.GGadget.Box.ShadowOuter: False
Gdraw.GGadget.Box.DoDepressedBackground: False
Gdraw.GGadget.Box.DrawDefault: False
Gdraw.GGadget.Box.GradientBG: False
Gdraw.GGadget.Box.NormalForeground: #d4d4d4
Gdraw.GGadget.Box.DisabledForeground: #525252
Gdraw.GGadget.Box.NormalBackground: #333333
Gdraw.GGadget.Box.DisabledBackground: #333333
Gdraw.GGadget.Box.PressedBackground: #999999
Gdraw.GGadget.Box.GradientStartCol: #333333
Gdraw.GGadget.Box.BorderBrightest: #525252
Gdraw.GGadget.Box.BorderBrighter: #525252
Gdraw.GGadget.Box.BorderDarker: #525252
Gdraw.GGadget.Box.BorderDarkest: #525252
Gdraw.GGadget.Box.BorderInnerCol: #525252
Gdraw.GGadget.Box.BorderOuterCol: #999999
Gdraw.GGadget.Box.ActiveBorder: #0f6bcf
Gdraw.GGadget.Box.BorderType: none
Gdraw.GGadget.Box.BorderShape: rect
Gdraw.GGadget.Box.BorderWidth: 0
Gdraw.GGadget.Box.Padding: 2
Gdraw.GGadget.Box.Radius: 0
Gdraw.GGadget.Font: 400 10pt Sans, Lucida Grande, Arial, Helvetica Neue

Gdraw.GGadget.Skip: 6
Gdraw.GGadget.LineSkip: 3
Gdraw.GGadget.FirstLine: 6
Gdraw.GGadget.LeftMargin: 6
Gdraw.GGadget.TextImageSkip: 4
Gdraw.GGadget.ImagePath: ~/FontForge/zDark.theme:~/FontForge/zDark.theme/zDark: /Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps/:=

Gdraw.GListMark.Box.BorderInner: True
Gdraw.GListMark.Box.BorderWidth: 1
Gdraw.GListMark.Box.Padding: 0
Gdraw.GListMark.Image: listmark.png
Gdraw.GListMark.DisabledImage: listmark-disabled.png
Gdraw.GListMark.Width: 6

Gdraw.GLabel.Box.BorderType: none
Gdraw.GLabel.Box.BorderWidth: 1
Gdraw.GLabel.Box.Padding: 0
Gdraw.GLabel.Font: 400 10pt Sans, Lucida Grande, Arial, Helvetica Neue

Gdraw.GButton.Box.BorderInner: True
Gdraw.GButton.Box.BorderOuter: False
Gdraw.GButton.Box.DoDepressedBackground: True
Gdraw.GButton.Box.DrawDefault: False
Gdraw.GButton.Box.BorderInnerCol: #999999
Gdraw.GButton.Box.BorderType: box
Gdraw.GButton.Box.BorderShape: roundrect
Gdraw.GButton.Box.Radius: 3
Gdraw.GButton.Font: 400 10pt Sans, Lucida Grande, Arial, Helvetica Neue
Gdraw.GButton.ShiftOnPress: False




Gdraw.GDropList.Box.NormalBackground: #242424
Gdraw.GDropList.Box.DisabledBackground: #242424
Gdraw.GDropList.Box.BorderInnerCol: #525252

Gdraw.GRadio.Box.BorderType: box
Gdraw.GRadio.Box.Padding: 0

Gdraw.GRadioOn.Box.DoDepressedBackground: False
Gdraw.GRadioOn.Box.PressedBackground: #0f6bcf
Gdraw.GRadioOn.Box.BorderType: box
Gdraw.GRadioOn.Box.BorderShape: rect
Gdraw.GRadioOn.Box.Padding: 0
Gdraw.GRadioOn.Image: radioon.png
Gdraw.GRadioOn.DisabledImage: radioon-disabled.png

Gdraw.GRadioOff.Box.DoDepressedBackground: False
Gdraw.GRadioOff.Box.PressedBackground: #333333
Gdraw.GRadioOff.Box.BorderType: box
Gdraw.GRadioOff.Box.BorderShape: rect
Gdraw.GRadioOff.Box.Padding: 0
Gdraw.GRadioOff.Image: radiooff.png
Gdraw.GRadioOff.DisabledImage: radio_off_disabled.png

Gdraw.GCheckBox.Box.BorderType: box
Gdraw.GCheckBox.Box.Padding: 0
Gdraw.GCheckBox.Font: 400 10pt Sans, Lucida Grande, Arial, Helvetica Neue

Gdraw.GCheckBoxOn.Box.DoDepressedBackground: False
Gdraw.GCheckBoxOn.Box.PressedBackground: #0f6bcf
Gdraw.GCheckBoxOn.Box.BorderType: box
Gdraw.GCheckBoxOn.Box.BorderShape: rect
Gdraw.GCheckBoxOn.Box.Padding: 3
Gdraw.GCheckBoxOn.Image: checkon.png
Gdraw.GCheckBoxOn.DisabledImage: checkon-disabled.png

Gdraw.GCheckBoxOff.Box.DoDepressedBackground: False
Gdraw.GCheckBoxOff.Box.PressedBackground: #333333
Gdraw.GCheckBoxOff.Box.BorderType: box
Gdraw.GCheckBoxOff.Box.BorderShape: rect
Gdraw.GCheckBoxOff.Box.Padding: 3
Gdraw.GCheckBoxOff.Image: checkoff.png
Gdraw.GCheckBoxOff.DisabledImage: checkoff-disabled.png

Gdraw.GVisibilityBox.Box.BorderType: none
Gdraw.GVisibilityBox.Box.Padding: 0

Gdraw.GVisibilityBoxOn.Box.BorderType: none
Gdraw.GVisibilityBoxOn.Box.Padding: 1
Gdraw.GVisibilityBoxOn.Image: visiblilityon.png
Gdraw.GVisibilityBoxOn.DisabledImage: check_on_disabled.png

Gdraw.GVisibilityBoxOff.Box.BorderType: none
Gdraw.GVisibilityBoxOff.Box.Padding: 1
Gdraw.GVisibilityBoxOff.Image: visiblilityoff.png
Gdraw.GVisibilityBoxOff.DisabledImage: check_off_disabled.png

Gdraw.GTextField.Box.BorderInner: True
Gdraw.GTextField.Box.NormalBackground: #242424
Gdraw.GTextField.Box.DisabledBackground: #242424
Gdraw.GTextField.Box.BorderShape: roundrect
Gdraw.GTextField.Box.Padding: 2
Gdraw.GTextField.Box.Radius: 3
Gdraw.GTextField.Font: 400 10pt Sans, Lucida Grande, Arial, Helvetica Neue


Gdraw.GComboBoxMenu.Box.Padding: 2


Gdraw.GNumericFieldSpinner.Box.BorderType: box
Gdraw.GNumericFieldSpinner.Box.BorderWidth: 0
Gdraw.GNumericFieldSpinner.Box.Padding: 2

Gdraw.GList.Box.BorderInner: True
Gdraw.GList.Box.BorderOuter: False
Gdraw.GList.Box.NormalBackground: #242424
Gdraw.GList.Box.DisabledBackground: #242424
Gdraw.GList.Box.BorderType: box
Gdraw.GList.Box.BorderShape: roundrect
Gdraw.GList.Box.Radius: 3
Gdraw.GList.Font: 400 10pt Sans, Lucida Grande, Arial, Helvetica Neue

Gdraw.GScrollBar.Box.BorderOuter: False
Gdraw.GScrollBar.Box.NormalBackground: #242424
Gdraw.GScrollBar.Box.DisabledBackground: #242424
Gdraw.GScrollBar.Box.BorderOuterCol: #242424
Gdraw.GScrollBar.Box.BorderType: none
Gdraw.GScrollBar.Box.BorderWidth: 0
Gdraw.GScrollBar.Box.Padding: 2
Gdraw.GScrollBar.StartTime: 300
Gdraw.GScrollBar.RepeatTime: 200
Gdraw.GScrollBar.Width: 13

Gdraw.GScrollBarThumb.Box.NormalForeground: #525252
Gdraw.GScrollBarThumb.Box.NormalBackground: #525252
Gdraw.GScrollBarThumb.Box.DisabledBackground: #525252
Gdraw.GScrollBarThumb.Box.BorderShape: roundrect
Gdraw.GScrollBarThumb.Box.BorderWidth: 0
Gdraw.GScrollBarThumb.Box.Padding: 3
Gdraw.GScrollBarThumb.Box.Radius: 3

Gdraw.GGroup.Box.NormalBackground: #333333
Gdraw.GGroup.Box.DisabledBackground: #333333
Gdraw.GGroup.Box.BorderType: box
Gdraw.GGroup.Box.BorderShape: rect
Gdraw.GGroup.Box.Padding: 0

Gdraw.GLine.Box.BorderBrighter: #999999
Gdraw.GLine.Box.BorderType: box
Gdraw.GLine.Box.BorderShape: rect
Gdraw.GLine.Box.BorderWidth: 1
Gdraw.GLine.Box.Padding: 0

Gdraw.GHVBox.Box.BorderType: none
Gdraw.GHVBox.Box.BorderShape: rect
Gdraw.GHVBox.Box.Padding: 0

Gdraw.GGroup.Box.NormalBackground: #333333
Gdraw.GGroup.Box.DisabledBackground: #333333
Gdraw.GGroup.Box.BorderType: box
Gdraw.GGroup.Box.BorderShape: rect
Gdraw.GGroup.Box.Padding: 0

Gdraw.GFlowBox.Box.BorderType: none
Gdraw.GFlowBox.Box.BorderWidth: 0
Gdraw.GFlowBox.Box.Padding: 0

Gdraw.GScroll1Box.Box.BorderType: none
Gdraw.GScroll1Box.Box.BorderWidth: 1
Gdraw.GScroll1Box.Box.Padding: 3

Gdraw.GMenuBar.Box.BorderOuter: False
Gdraw.GMenuBar.Box.NormalBackground: #242424
Gdraw.GMenuBar.Box.BorderShape: rect
Gdraw.GMenuBar.Box.BorderWidth: 4
Gdraw.GMenuBar.Font: 400 10pt Sans, Lucida Grande, Arial, Helvetica Neue

Gdraw.GMenu.Box.BorderOuter: True
Gdraw.GMenu.Box.BorderOuterCol: #525252
Gdraw.GMenu.Box.BorderShape: rect
Gdraw.GMenu.Box.Padding: 6
Gdraw.GMenu.Font: 400 10pt Sans, Lucida Grande, Arial, Helvetica Neue
Gdraw.GMenu.MacIcons: False
Gdraw.GMenu.3DLook: True
Gdraw.GMenu.Grab: True

Gdraw.GMatrixEdit.Box.NormalBackground: #242424
Gdraw.GMatrixEdit.Box.DisabledBackground: #333333
Gdraw.GMatrixEdit.Box.BorderType: box
Gdraw.GMatrixEdit.Box.BorderShape: rect
Gdraw.GMatrixEdit.Box.BorderWidth: 3
Gdraw.GMatrixEdit.Box.Padding: 0
Gdraw.GMatrixEdit.Font: 400 10pt Sans, Lucida Grande, Arial, Helvetica Neue

Gdraw.GMatrixEdit.TitleBG: #525252
Gdraw.GMatrixEdit.TitleFG: #d4d4d4
Gdraw.GMatrixEdit.TitleDivider: #525252
Gdraw.GMatrixEdit.RuleCol: #525252
Gdraw.GMatrixEdit.FrozenCol: #ff4f69
Gdraw.GMatrixEdit.ActiveCol: #d4d4d4
Gdraw.GMatrixEdit.ActiveBG: #0f6bcf
Gdraw.GMatrixEdit.TitleFont: 400 10pt Sans, Lucida Grande, Arial, Helvetica Neue

Gdraw.GMatrixEditButton.Box.BorderInner: True
Gdraw.GMatrixEditButton.Box.NormalBackground: #242424
Gdraw.GMatrixEditButton.Box.DisabledBackground: #333333
Gdraw.GMatrixEditButton.Box.BorderWidth: 1

Gdraw.GDrawable.Box.BorderType: box
Gdraw.GDrawable.Box.BorderWidth: 0
Gdraw.GDrawable.Box.Padding: 0

Gdraw.GTabSet.Box.BorderInner: True
Gdraw.GTabSet.Box.ActiveInner: True
Gdraw.GTabSet.Box.BorderType: box
Gdraw.GTabSet.Box.BorderShape: roundrect
Gdraw.GTabSet.Box.BorderWidth: 0
Gdraw.GTabSet.Box.Radius: 3
Gdraw.GTabSet.Font: 400 10pt system-ui,Deja Vu Sans,Lucida Grande,sans
Gdraw.GTabSet.CloseColor: #ff0000


